version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
serial:
  port: /dev/ttyS1
  adapter: zstack
  baudrate: 115200
  rtscts: false
advanced:
  log_level: info
  transmit_power: 20
homeassistant:
  enabled: true
  discovery_topic: homeassistant
frontend:
  enabled: true
  port: 8080
  host: 0.0.0.0
devices:
  '0x001788010ebc5503':
    friendly_name: 'Big Bedroom Lamp'
